export const QUERY_KEYS = {
  PROJECT_CONFIG: {
    GET: "GET_PROJECT_CONFIG",
  },
  NOTIFICATIONS: {
    SEND_BROADCAST_TO_ALL_USERS: "SEND_BROADCAST_TO_ALL_USERS",
  },

  USERS: {
    GET_REFERRALS: "GET_REFERRALS",
  },
  TON_API: {
    BALANCES: "BALANCES",
    BALANCES_CURRENCY: "BALANCES_CURRENCY",
    MASTER_ADDRESS_JETTON: "MASTER_ADDRESS_JETTON",
    JETTON_META: "JETTON_META",
  },
};
