export enum WITHDRAW_STATUS {
  PENDING = "PENDING",
  IN_PROGRESS = "IN_PROGRESS",
  CONFIRMED = "CONFIRMED",
  CANCELED = "CANCELED",
}

export enum WITHDRAW_TYPE {
  SKIN = "SKIN",
  GOLD = "GOLD",
}
