export enum TRANSACTION_TYPE {
  MARKET = "MARKET",
  DEPOSIT = "DEPOSIT",
  WITHDRAWAL = "WITHDRAWAL",
  REFERRAL_BONUS = "REFERRAL_BONUS",
}
export enum TRANSACTION_STATUS {
  PENDING = "PENDING",
  COMPLETED = "COMPLETED",
  CANCELED = "CANCELED",
}
